### ISSUE TITLE
Integrate hemajoo-foundation project to Travis

### ISSUE THREAD

**Issue by ressec** [ressec/hemajoo-foundation#14]
## Purpose

Integrate the **hemajoo-foundation** project with **Travis** so that Travis can trigger automatic builds when commits and pull requests are issued in **GitHub**. It can also trigger automatic deployments of generated artefacts in the repository manager.

Here is the procedure to configure the **Eclipse** project and the **Travis** integration between **GitHub** and **Travis**.

### Create a Travis YAML file

In the git root folder of the project, create a **.travis.yml** file that contains the build information.

Here is an example of such a **.travis-yml** file:

```
sudo: false

language: 
  - java

jdk: 
  - oraclejdk8

services:
  - docker
  - postgresql

addons:
  - postgresql: "9.6"

cache:
  - $HOME/.m2
  #- target/

before_script:

script: mvn clean package -f hemajoo-foundation-parent/pom.xml

deploy:
  provider: script
  script: "cp hemajoo-foundation-parent/etc/deploy-settings.xml $HOME/.m2/settings.xml && mvn deploy -f hemajoo-foundation-parent/pom.xml"
  skip_cleanup: false
  on:
    # Set 'tags' to:
    # . 'true'  which will force the deployment of the artifact after a successful build only when the 
    #              commit is tagged. So even if a merge request to 'master' is successful, the built artifact 
    # .            will not be deployed to the repository.
    # . 'false' which will force the deployment of the artifact after a successful build only when merged on the 'master' branch.
    tags: false

notifications:
  email:
    recipients:
    - christophe.resse@gmail.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      - heliosphere-team:<**token**>#travis-hemajoo
```

### deploy-settings.xml file

Create an 'etc' folder in the parent project and under this folder, create a **deploy-settings.xml** file. 

Here is an example of the content of such a file:

```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          http://maven.apache.org/xsd/settings-1.0.0.xsd">
	<servers>
		<server>
			<id>nexus-snapshots</id>
			<username>${CI_DEPLOY_USERNAME}</username>
			<password>${CI_DEPLOY_PASSWORD}</password>
		</server>

		<server>
			<id>nexus-releases</id>
			<username>${CI_DEPLOY_USERNAME}</username>
			<password>${CI_DEPLOY_PASSWORD}</password>
		</server>
	</servers>

</settings>
```

## 2. Travis Web Site

- Go to: [https://travis-ci.org/ressec](https://travis-ci.org/ressec)
- Select the repository that you want to integrate with **Travis**
- Activate the repository
- Select the 'settings' option of the repository and ajust the values according to your needs
- Create the following environment variables:
   - CI_DEPLOY_USERNAME
   - CI_DEPLOY_PASSWORD
- In the **Cron** jobs, define a job to run on a daily basis the build
