### ISSUE TITLE
Set the Travis build run static code analysis on Sonar Cloud

### ISSUE THREAD

**Issue by ressec** [ressec/hemajoo-foundation#51]
Add the following lines in the Travis build file...

```
addons:
 . . .
  sonarcloud:
    organization: "ressec-github"
    token:
      secure: "${SONAR_TOKEN}"
```

and declare in the build settings the **SONAR_TOKEN** variable.

and ensure the script block contains required information:

```
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -f hemajoo-foundation-parent/pom.xml
```
